# Generated by Django 4.2.6 on 2023-10-09 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=200,
                                          verbose_name='Name')),
                ('slug', models.SlugField(max_length=200)),
                ('url', models.CharField(blank=True,
                                         max_length=1000,
                                         verbose_name='URL')),
                ('parent', models.ForeignKey(
                    blank=True,
                    default=None,
                    null=True,
                    on_delete=django.db.models.deletion.SET_DEFAULT,
                    to='menu.menu',
                    verbose_name='Parent to this element')
                 ),
            ],
            options={
                'verbose_name': 'Menu',
                'ordering': ['name'],
            },
        ),
    ]
